name: Run checks

on:
    push:
        branches-ignore:
            - main

permissions:
    contents: read

jobs:
    run-checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 26
            - run: npm ci
            - run: npx better-npm-audit audit
            - run: npm run build
            - run: npm test
